apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # These are deployment set labels.
  labels:
    purpose: dp-demo
    project: roboshop
spec:
  replicas: 4
  selector: 
  # These labels are used to select pods.
    matchLabels:
      purpose: headless-svc-demo
      project: roboshop  

  # pod definition    
  template:
    metadata:
      labels:
        purpose: headless-svc-demo
        project: roboshop
    spec:    
      containers:
      - name: nginx
      # Deployment respects image changes.
        image: nginx:latest
