apiVersion: v1
kind: pod
metadata: 
  name: affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In 
            values:
            - us-east-1c
          - key: disktype
            operator: In 
            values:
            - ssd
  containers:
  - name: nginx
    image: nginx 
    imagePullPolicy: Always


