apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  selector:
    matchLabels:
      app: store
  replicas: 2
  # pod definition
  template:
    metadata:
      labels:
        app: store
    spec:
      affinity:
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution:
          #pod labels
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"    
      containers:
      - name: redis-server
        image: redis:3.2-alpine  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-store  
  template:
    metadata:
      labels:
        app: web-store
    spec:    
      affinity:
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: web
                  operator: In
                  values: 
                  - store    
              topologyKey: "kubernetes.io/hostname"    
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
                - store
            topologyKey: "kubernetes.io/hostname"   
      containers:
      - name: web-app
        image: nginx:1.16-alpine             


